version: '3'

services:
  vault:
    image: vault:{{ vault_version }}
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_LOCAL_CONFIG: >
        {
          "listener": [{ "tcp": { "address" : "0.0.0.0:8200", "tls_disable" : 1 }}],
          "api_addr": "http://0.0.0.0:8200",
          "storage": { "mysql": { "address": "{{ db_url }}", "username": "{{ rds_username }}", "password": "{{ rds_password }}", "database": "vault", "ha_enabled": "false" }},
          "ui": true
        }
    cap_add:
      - IPC_LOCK
    command: ["server", "-log-level=trace"]


   
