version: '3'

services:
  vault:
    image: vault:{{ vault_version }}
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_ADDR: 'http://localhost:8200'
      VAULT_DATABASE_MYSQL_DATASOURCE_NAME: "{{ rds_username }}:{{ rds_password }}@({{ db_url }}:3306)/vaultdb"


      
